#
# Module manifest for module 'biz.dfch.PS.System.Logging'
#
# Generated by: Ronald Rink
#
# Generated on: 10/13/2014
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'biz.dfch.PS.System.Logging.psm1'

# Version number of this module.
ModuleVersion = '1.0.1.20141115'

# ID used to uniquely identify this module
GUID = 'bb42dde0-0260-40bc-85e2-d8b6de1b5c0e'

# Author of this module
Author = 'Ronald Rink'

# Company or vendor of this module
CompanyName = 'd-fens GmbH'

# Copyright statement for this module
Copyright = '(c) 2014 d-fens GmbH. Distributed under Apache 2.0 license.'

# Description of the functionality provided by this module
Description = 'Module for logging messages from PowerShell to arbitrary output formats'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @(
# )

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
	'log4net.dll'
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @(
	'Import-Module.ps1'
)

# ModuleToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
	'Out-Message.ps1'
)

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
	'biz.dfch.PS.System.Logging.xml'
	,
	'Log4netConfiguration.xml'
	,
	'log4net.xml'
	,
	'LICENSE'
	,
	'NOTICE'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{
	"MODULEVAR" = "biz_dfch_PS_System_Logging"
}

# HelpInfo URI of this module
HelpInfoURI = 'http://dfch.biz/biz/dfch/PS/System/Logging/'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

